copy p1\pull\conf_mesh p1\pull\conf
copy p2\pull\conf_mesh p2\pull\conf
copy p3\pull\conf_mesh p3\pull\conf
copy p4\pull\conf_mesh p4\pull\conf
copy p5\pull\conf_mesh p5\pull\conf
copy p6\pull\conf_mesh p6\pull\conf
copy p7\pull\conf_mesh p7\pull\conf
copy p8\pull\conf_mesh p8\pull\conf
copy p9\pull\conf_mesh p9\pull\conf
copy p10\pull\conf_mesh p10\pull\conf
copy p11\pull\conf_mesh p11\pull\conf
copy p12\pull\conf_mesh p12\pull\conf

copy p1\push\conf_mesh p1\push\conf
copy p2\push\conf_mesh p2\push\conf
copy p3\push\conf_mesh p3\push\conf
copy p4\push\conf_mesh p4\push\conf
copy p5\push\conf_mesh p5\push\conf
copy p6\push\conf_mesh p6\push\conf
copy p7\push\conf_mesh p7\push\conf
copy p8\push\conf_mesh p8\push\conf
copy p9\push\conf_mesh p9\push\conf
copy p10\push\conf_mesh p10\push\conf
copy p11\push\conf_mesh p11\push\conf
copy p12\push\conf_mesh p12\push\conf
