copy p1\pull\*.java p2\pull\
copy p1\pull\*.java p3\pull\
copy p1\pull\*.java p4\pull\
copy p1\pull\*.java p5\pull\
copy p1\pull\*.java p6\pull\
copy p1\pull\*.java p7\pull\
copy p1\pull\*.java p8\pull\
copy p1\pull\*.java p9\pull\
copy p1\pull\*.java p10\pull\
copy p1\pull\*.java p11\pull\
copy p1\pull\*.java p12\pull\

copy p1\push\*.java p2\push\
copy p1\push\*.java p3\push\
copy p1\push\*.java p4\push\
copy p1\push\*.java p5\push\
copy p1\push\*.java p6\push\
copy p1\push\*.java p7\push\
copy p1\push\*.java p8\push\
copy p1\push\*.java p9\push\
copy p1\push\*.java p10\push\
copy p1\push\*.java p11\push\
copy p1\push\*.java p12\push\

del /q p1\pull\*.class
del /q p2\pull\*.class
del /q p3\pull\*.class
del /q p4\pull\*.class
del /q p5\pull\*.class
del /q p6\pull\*.class
del /q p7\pull\*.class
del /q p8\pull\*.class
del /q p9\pull\*.class
del /q p10\pull\*.class
del /q p11\pull\*.class
del /q p12\pull\*.class

del /q p1\push\*.class
del /q p2\push\*.class
del /q p3\push\*.class
del /q p4\push\*.class
del /q p5\push\*.class
del /q p6\push\*.class
del /q p7\push\*.class
del /q p8\push\*.class
del /q p9\push\*.class
del /q p10\push\*.class
del /q p11\push\*.class
del /q p12\push\*.class

del /q p1\Peer.class
del /q p2\Peer.class
del /q p3\Peer.class
del /q p4\Peer.class
del /q p5\Peer.class
del /q p6\Peer.class
del /q p7\Peer.class
del /q p8\Peer.class
del /q p9\Peer.class
del /q p10\Peer.class
del /q p11\Peer.class
del /q p12\Peer.class
