copy p1\conf_pull p1\conf
copy p2\conf_pull p2\conf
copy p3\conf_pull p3\conf
copy p4\conf_pull p4\conf
copy p5\conf_pull p5\conf
copy p6\conf_pull p6\conf
copy p7\conf_pull p7\conf
copy p8\conf_pull p8\conf
copy p9\conf_pull p9\conf
copy p10\conf_pull p10\conf
copy p11\conf_pull p11\conf
copy p12\conf_pull p12\conf
